### ISSUE TITLE
Instructions for Configuring Camera

### ISSUE THREAD

**Issue by theqwertman** [HipsterSloth/psmove-unity5#15]
The wiki states, "If your camera is setup properly then this should show you the images from the camera at 320x240@167Hz."

My camera is reporting 640x480@60Hz. How do I fix this?

**Comment by HipsterSloth** [comment]
Ah sorry. That documentation is old. The old version of the camera test app ran at 320x240@167. However this isn't the resolution/framerate that is used for psmoveapi because the effective tracking range is too short at this resolution. Since we want the camera test app to be representative of what psmoveapi is seeing I switched the camera test app to match.

**Comment by HipsterSloth** [comment]
The wiki has been updated. Closing this issue.
