### ISSUE TITLE
Extra event calls on Button press.

### ISSUE THREAD

**Issue by MHDante** [HipsterSloth/psmove-unity5#21]
It seems that the C# events are being called more than once on a single button press. 

The check done here: 

https://github.com/HipsterSloth/psmove-unity5/blob/master/Assets/psmove-unity5/PSMoveData.cs#L230

seems to be causing it. I've removed it on my local build. However, I'm not too sure of the implications of doing so. Any ideas as to why this check is needed?

**Comment by HipsterSloth** [comment]
Good catch! If you want to make a PR with that change I'm happy to take it. Alternatively I can just make it locally to if that's a hassle.

Short version:
The check to see if this sequence data changed is actually an artifact from psmove-ue4 code I ported this code from that is now no longer necessary. So I think it's actually the right thing to skip that sequence number check. 

Long version:
The RawControllerData.ComponentRead() method is supposed to read controller updates in the main thread from the worker thread. Every time the worker thread posts new controller data it increments the SequenceNumber. This is there to tell if RawControllerData.ComponentRead() actually got new data or not. Since the controller component on the main thread can poll faster than the worker thread posts it's possible you can get stale data (which is fine). There used to be other flags that the worker thread would send to the component that it was supposed to only consider once when the data was fresh. Those flags are no longer present and I think I mistakenly put the previous button state in there trying to guard against the very thing I ended up causing: multiple button press events. We actually do want to stomp the previous button state every time ComponentRead() gets called, as you have setup locally. That way GetButtonPressedThisFrame() will only return true for one frame like we expect.

**Comment by MHDante** [comment]
Yeah, I thought it was the update thread hitting this faster than the worker thread. I'll add it to a PR I'll test and post on Monday.

**Comment by HipsterSloth** [comment]
Closing now that the PR is merged in. Thanks again!
